# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(help_text='(Required) A short         description of the wanted item.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='(Optional) A popup description         that gives more context and information to the request.')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
