# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-01 05:41
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.utils.timezone
import markdownx.models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# base.migrations.0004_auto_20170503_2021

class Migration(migrations.Migration):

    replaces = [('base', '0001_initial'), ('base', '0002_auto_20170414_1551'), ('base', '0003_announcement_ccontent'), ('base', '0004_auto_20170503_2021'), ('base', '0005_remove_announcement_content'), ('base', '0006_auto_20170504_1128')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, help_text='The date this announcement should go live')),
                ('expire_date', models.DateField(default=django.utils.timezone.now, help_text='The date this announcement should expire')),
                ('event_date', models.DateField(blank=True, default=None, help_text='\n        (Optional) If there is a date associated with this announcement, then put it here\n        ', null=True)),
                ('override', models.BooleanField(default=True, help_text='(Optional) Override. If box is unchecked,             announcement will immediately turn off.')),
                ('content', markdownx.models.MarkdownxField(blank=True, help_text='(Optional) Larger content block for announcement')),
                ('link', models.URLField(blank=True, help_text='(Optional) A pertinent url for the announcement')),
                ('slug', models.CharField(blank=True, help_text='A short description of announcement', max_length=500, unique=True)),
                ('headline', models.CharField(default='HEADLINE', help_text='(Required) The short headline of the announcement', max_length=200, verbose_name='The short headline for the announcement')),
                ('primary_image', models.ImageField(blank=True, help_text='(Optional) Background image for announcement', upload_to='', verbose_name='Optional announcement background image')),
            ],
            options={
                'verbose_name_plural': 'Announcements',
                'verbose_name': 'Announcement',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_file', models.FileField(help_text='Upload file here', max_length=200, upload_to='downloads/')),
                ('publish_to_frontpage', models.BooleanField(default=False, help_text='Should this show on the front page in the downloads list?')),
                ('display_name', models.CharField(default='', help_text='A short descriptive display name', max_length=100)),
                ('file_description', models.CharField(blank=True, help_text='Optional description field (rarely used)', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalNewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_publisher', models.CharField(help_text='The publisher of the article', max_length=100)),
                ('news_slug', models.CharField(blank=True, help_text='A short description of article', max_length=500)),
                ('external_url', models.URLField(help_text='The URL at which the article resides')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, help_text='The date the article was originally published')),
            ],
            options={
                'verbose_name_plural': 'ExternalNewsArticles',
                'verbose_name': 'ExternalNewsArticle',
            },
        ),
        migrations.CreateModel(
            name='VolunteerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(help_text="Volunteer's name, like 'Glenn Herlihy'", max_length=200)),
                ('volunteer_title_blurb', models.CharField(blank=True, help_text="Volunteer's title, like 'co-founder'", max_length=200)),
                ('volunteer_email', models.EmailField(max_length=254)),
                ('volunteer_is_active', models.BooleanField(default=True, help_text='Is volunteer active? Unchecked turns off volunteer.')),
                ('volunteer_sort_order', models.IntegerField(default=1, help_text='A higher number means that person will be listed first.')),
            ],
            options={
                'verbose_name_plural': 'VolunteerContacts',
                'verbose_name': 'VolunteerContact',
            },
        ),
        migrations.CreateModel(
            name='WorkPartyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_party_date', models.DateField(default=django.utils.timezone.now, help_text='The date the article was originally published')),
                ('work_party_time_start', models.TimeField(default=datetime.time(10, 0), help_text='The time that the work party starts')),
                ('work_party_time_end', models.TimeField(default=datetime.time(14, 0), help_text='The time that the work party ends')),
            ],
            options={
                'verbose_name_plural': 'Work Party Events',
                'verbose_name': 'Work Party Event',
            },
        ),
    ]
