# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 22:51
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, help_text='(Optional) Larger content block for announcement'),
        ),
    ]
