# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-01 06:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_squashed_0006_auto_20170504_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) Larger content block for announcement'),
        ),
    ]
