# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 03:21
from __future__ import unicode_literals

from django.db import migrations


def migrate_markdown_to_richtext(apps, schema_editor):
    Announcement = apps.get_model("base", "Announcement")

    for ann in Announcement.objects.all():
        ann.ccontent = ann.content
        ann.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_announcement_ccontent'),
    ]

    operations = [
        migrations.RunPython(migrate_markdown_to_richtext)
    ]
