# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-01 06:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(Required) Name of the committee', max_length=100)),
                ('main_contact', models.EmailField(blank=True, help_text='Main email contact for committee', max_length=254)),
                ('slug', models.SlugField(blank=True, help_text='(Optional) An url friendly         short description.', unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='A friendly description of the         committee accessible to the public.')),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, help_text='(Optional) Author of the meeting notes', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='The date the meeting took place')),
                ('notes', ckeditor.fields.RichTextField(blank=True, help_text='(Optional) Cut and paste meeting notes here')),
                ('override', models.BooleanField(default=True, help_text='(Optional) Override. If box is unchecked,             meeting will not be shown on website.')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(blank=True, help_text='(Recommended) Choose the committee this meeting belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='committee.Committee')),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
            },
        ),
    ]
