# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 03:39
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_auto_20170410_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='notes',
            field=markdownx.models.MarkdownxField(blank=True, help_text='(Optional) Cut and paste meeting notes here'),
        ),
    ]
