# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 11:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_auto_20170414_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='A friendly description of the         committee accessible to the public.'),
        ),
    ]
