# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 03:21
from __future__ import unicode_literals

from django.db import migrations


def migrate_markdown_to_richtext(apps, schema_editor):
    Meeting = apps.get_model("committee", "Meeting")

    for meeting in Meeting.objects.all():
        meeting.mnotes = meeting.notes
        meeting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0005_meeting_mnotes'),
    ]

    operations = [
        migrations.RunPython(migrate_markdown_to_richtext)
    ]
