# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0007_remove_meeting_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='mnotes',
            new_name='notes',
        ),
    ]
