# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_remove_classevent_class_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classevent',
            old_name='cclass_description',
            new_name='class_description',
        ),
    ]
