# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-01 06:55
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='(Required) The short title of the class', max_length=200, verbose_name='The short title of the class')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, help_text='(Required) The date that you want to publish the class on the website', verbose_name='date to publicize posting')),
                ('expire_date', models.DateField(default=django.utils.timezone.now, help_text='(Required) The date that you want to unpublish the class on the website', verbose_name='date to expire posting')),
                ('event_date', models.DateField(help_text='(Required) The date of the event', verbose_name='date class is held')),
                ('event_start_time', models.TimeField(blank=True, default=datetime.time(10, 0), help_text='(Required) The starting time of the class', verbose_name='time class starts')),
                ('event_end_time', models.TimeField(blank=True, default=datetime.time(14, 0), help_text='(Required) The end time of the class', verbose_name='time class ends')),
                ('ticket_link', models.URLField(blank=True, help_text='(Optional) An url link where to get tickets', verbose_name='link to tickets')),
                ('class_description', ckeditor.fields.RichTextField(blank=True, help_text='(Optional) Desciption of class (can be long) with formatting')),
                ('class_primary_image', models.ImageField(blank=True, help_text='(Optional) Primary image for the class', upload_to='', verbose_name='optional class image')),
                ('class_location', models.CharField(blank=True, default='S. Dakota Street and 16th Avenue South', help_text='(Optional) Describe in text the location of the event', max_length=300, verbose_name='text of location')),
                ('class_location_link', models.URLField(blank=True, default='https://goo.gl/maps/fpdzyHy5kjr', help_text='(Optional) Using a service like Google maps, provide a link to location.', verbose_name='Map link to class')),
                ('class_slug_url', models.SlugField(blank=True, help_text='(Optional) An url friendly short description.              Must be unique to each event e.g brew-your-own-kombucha-feb-2015.', unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='(Optional) Main pricing for event.  Putting in price helps with advertisement', max_digits=6)),
            ],
        ),
    ]
