# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-01 06:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_location', models.CharField(blank=True, help_text='(Optional) Description of location', max_length=200)),
                ('greater_area', models.CharField(blank=True, help_text='(Optional) Description of area like Phase2 Upper', max_length=200)),
                ('geo_location', geoposition.fields.GeopositionField(blank=True, help_text='Approximate gps coordinates of location', max_length=42, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='MapCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='(Optional) On map, main         folder to categorize this plant, e.g. Trees, Shrubs, Herbals.  If left blank, will not         be displayed on map.  More folders can be added in admin interface.', max_length=100)),
                ('icon', models.ImageField(blank=True, help_text='Primary icon for category.  Please use         svg format for optimum performance.', upload_to='', verbose_name='category icon')),
            ],
            options={
                'verbose_name': 'Map Folder Category',
                'verbose_name_plural': 'Map Folder Category',
            },
        ),
        migrations.CreateModel(
            name='MapSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(blank=True, help_text='(Optional) On map,         subfolder to categorize this plant, e.g. under trees, we would have -- Apples, Nuts,         etc.  If left blank, will not be displayed on map.  More subfolders can be added', max_length=100)),
                ('icon', models.ImageField(blank=True, help_text='Primary icon for subcategory.  Please use         svg format for optimum performance.', upload_to='', verbose_name='subcategory icon')),
            ],
            options={
                'verbose_name': 'Map Subfolder Category',
                'verbose_name_plural': 'Map Subfolder Category',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(blank=True, help_text="(Optional) A friendly plant name, like 'Charlie the Apple Tree'", max_length=100)),
                ('latin_name', models.CharField(blank=True, help_text='(Optional) Latin name', max_length=150)),
                ('name', models.CharField(help_text='Common Name (required)', max_length=150)),
                ('text', ckeditor.fields.RichTextField(blank=True, help_text='(Optional) Descriptive text for plant (put anything here)')),
                ('primary_picture', models.ImageField(blank=True, help_text='(Optional) primary image', upload_to='')),
                ('year_planted', models.IntegerField(blank=True, help_text='(Optional) Year planted at Beacon Food forest.  Use -1 for unknown.', null=True)),
                ('site_code', models.CharField(help_text='(Required) A unique code for plant, comprised of year planted +         sequential number of plant.  e.g. 1501 (2015,first plant)', max_length=20, unique=True)),
                ('url_slug', models.SlugField(blank=True, help_text='(Optional) An url friendly short description.        Must be unique to each plant e.g julies-quince', unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('alive', models.BooleanField(default=True, help_text='Is plant alive? Unchecked        declares dead but maintains info for historical purposes.')),
                ('published', models.BooleanField(default=True, help_text='If you want to remove        the plant from being listed on the site, then uncheck this.')),
                ('geo_location', geoposition.fields.GeopositionField(blank=True, help_text='Exact gps coordinates of location of plant', max_length=42, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='(Optional) On map, main folder to categorize this plant, e.g. Trees, Shrubs,         Herbals.  If left blank, will not be displayed on map.  More folders can be added        in admin interface.', null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.MapCategory')),
                ('location', models.ForeignKey(blank=True, help_text='Assign a location (made separately)', null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Location')),
                ('subcategory', models.ForeignKey(blank=True, help_text='(Optional) On map, subfolder to categorize this plant, e.g. under trees,         we would have -- Apples, Nuts, etc.  If left blank, will not be displayed on map.          More subfolders can be added in admin interface.', null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.MapSubCategory')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'plant',
                'verbose_name_plural': 'plants',
            },
        ),
    ]
