# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170503_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
    ]
