# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 06:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170504_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpartyevent',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) Description of work party (can be long) with formatting', verbose_name='Description of work party'),
        ),
        migrations.AddField(
            model_name='workpartyevent',
            name='location',
            field=models.CharField(blank=True, default='S. Dakota Street and 16th Avenue South', help_text='(Optional) Describe in text the location of the event.  Defaults to Beacon Food Forest.', max_length=300, verbose_name='text of location'),
        ),
        migrations.AddField(
            model_name='workpartyevent',
            name='location_link',
            field=models.URLField(blank=True, default='https://goo.gl/maps/fpdzyHy5kjr', help_text='(Optional) Using a service like Google maps, provide a link to location.                   Defaults to Beacon Food Forest.', verbose_name='Map link to work party'),
        ),
        migrations.AddField(
            model_name='workpartyevent',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='(Optional) Primary image for the work party', upload_to='', verbose_name='optional image(overrides default)'),
        ),
    ]
