# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190307_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpartyevent',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, help_text='(Optional) An url friendly short description.', unique=True),
        ),
    ]
