# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 04:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_committee_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='mnotes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) Cut and paste meeting notes here'),
        ),
    ]
